name: Backend CI
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
#env:
#  docker_username: ${{ secrets.DOCKER_USERNAME }}
#  docker_password: ${{ secrets.DOCKER_PASSWORD }}
#  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2   
      - name: Upload Backend Code
        uses: actions/upload-artifact@v2
        with:
          name: backend-code
          path: backend 

  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Backend Code
        uses: actions/download-artifact@v2
        with: 
          name: backend-code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
        #with:
        #  go-version: '^1.13.1'   
      - name: Verify Go
        run: go mod verify  
      - name: Build
        run: go build
      - name: Upload Backend Binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-bin
          path: ./backend
