name: Frontend CI
on:
  push:
    branches:
      - f/**
      - dev
      - main
      - staging
  pull_request:
    branches:
      - f/**
      - dev
      - main
      - staging
#env:
#  docker_username: ${{ secrets.DOCKER_USERNAME }}
#  docker_password: ${{ secrets.DOCKER_PASSWORD }}
#  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2   
      - name: Upload Frontend Code
        uses: actions/upload-artifact@v2
        with:
          name: frontend-code
          path: frontend 

  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Frontend Code
        uses: actions/download-artifact@v2
        with: 
          name: frontend-code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
        #with:
        #  go-version: '^1.13.1'   
      - name: Verify Go
        run: go mod verify          
      - name: Build
        run: go build
      - name: Upload Frontend Binary
        uses: actions/upload-artifact@v2
        with:
          name: frontend-bin
          path: .

  Test:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with: 
          name: frontend-code
          path: .
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Verify Go
        run: go mod verify          
        #with:
        #  go-version: '^1.13.1'   
      - name: Test
        run: go test 
